### ISSUE TITLE
When I run pip install -r requirements.txt, a error occurred

### ISSUE THREAD

**Issue by doubleheiker** [lanqian528/chat2api#129]
```
Defaulting to user installation because normal site-packages is not writeable
Collecting fastapi (from -r requirements.txt (line 1))
  Using cached fastapi-0.112.0-py3-none-any.whl.metadata (27 kB)
Collecting curl_cffi (from -r requirements.txt (line 2))
  Using cached curl_cffi-0.7.1.tar.gz (133 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 16, in <module>
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 146, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 278, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 286, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 630, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 650, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 216, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-j_ra7e7u/overlay/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "scripts/build.py", line 47, in <module>
          arch = detect_arch()
                 ^^^^^^^^^^^^^
        File "scripts/build.py", line 44, in detect_arch
          raise Exception(f"Unsupported arch: {uname}")
      Exception: Unsupported arch: uname_result(system='FreeBSD', node='s8.serv00.com', release='14.1-RELEASE-p1', version='FreeBSD 14.1-RELEASE-p1 #1 releng/14.1-n267682-0892dff10444-dirty: Thu Jun 20 02:44:04 CEST 2024     root@pkg1.admin.net.pl:/usr/obj/usr/src/amd64.amd64/sys/devil', machine='amd64')
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
Is that due to my server is FreeBSD？

**Comment by lanqian528** [comment]
plz use ubuntu 22
