### ISSUE TITLE
Showing Error

### ISSUE THREAD

**Issue by Niansuh** [lanqian528/chat2api#46]
===== Application Startup at 2024-05-21 09:23:40 =====

2024-05-21 09:23:47,369 | INFO | ------------------------------------------------------------
2024-05-21 09:23:47,370 | INFO | Chat2Api v1.1.2 | https://github.com/lanqian528/chat2api
2024-05-21 09:23:47,370 | INFO | ------------------------------------------------------------
2024-05-21 09:23:47,370 | INFO | Environment variables:
2024-05-21 09:23:47,370 | INFO | API_PREFIX:        yyds
2024-05-21 09:23:47,370 | INFO | AUTHORIZATION:     []
2024-05-21 09:23:47,370 | INFO | CHATGPT_BASE_URL:  ['https://chatgpt.com']
2024-05-21 09:23:47,370 | INFO | ARKOSE_TOKEN_URL:  []
2024-05-21 09:23:47,370 | INFO | PROXY_URL:         []
2024-05-21 09:23:47,370 | INFO | HISTORY_DISABLED:  True
2024-05-21 09:23:47,370 | INFO | POW_DIFFICULTY:    000032
2024-05-21 09:23:47,370 | INFO | RETRY_TIMES:       3
2024-05-21 09:23:47,370 | INFO | ENABLE_GATEWAY:    True
2024-05-21 09:23:47,370 | INFO | CONVERSATION_ONLY: False
2024-05-21 09:23:47,370 | INFO | ------------------------------------------------------------
Traceback (most recent call last):
  File "/app/app.py", line 9, in <module>
    uvicorn.run("chat2api:app", host="0.0.0.0", port=5005)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/chat2api.py", line 14, in <module>
    from utils.authorization import verify_token, token_list
  File "/app/utils/authorization.py", line 6, in <module>
    from chatgpt.refreshToken import rt2ac
  File "/app/chatgpt/refreshToken.py", line 18, in <module>
    os.makedirs(DATA_FOLDER)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: 'data'

**Comment by lanqian528** [comment]
权限问题，自己修改一下权限吧

**Comment by lanqian528** [comment]
use root user to run the docker

**Comment by lanqian528** [comment]
> one more question how to use chatgpt login free api?

I don't understand what do you mean.

**Comment by lanqian528** [comment]
> > > one more question how to use chatgpt login free api?
> > 
> > 
> > I don't understand what do you mean.
> 
> i mean how to use chatgpt web free login api
> 
> ![image](https://private-user-images.githubusercontent.com/139365289/332858892-fa9844e6-bedc-49b3-bf35-afd3fe89a3f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTI4NDYsIm5iZiI6MTcxNjM5MjU0NiwicGF0aCI6Ii8xMzkzNjUyODkvMzMyODU4ODkyLWZhOTg0NGU2LWJlZGMtNDliMy1iZjM1LWFmZDNmZTg5YTNmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNTQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Mzg0MzYzMWI4ZjU2MjY4YmFjODVmNzFjYjQ4YTg3NTRkM2MzMDFkYjEwODAwZTJkZGIwNWNiYWRkOWYxZTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aTw1KjByw0tLFK4gmt18MMMLQytuKJCzwwyFfbH8QbU)

My project don't support logging in.

**Comment by lanqian528** [comment]
> Also, is there any way to deploy in a custom domain

Ask chatgpt,plz

**Comment by lanqian528** [comment]
> and showing this error 500 Internal Server Error. after rebuilding 1 or 2 times the ui show
> 
> {deploy on hugging face}
> 
> ![image](https://private-user-images.githubusercontent.com/139365289/332879608-5aa1c250-ac58-4d83-a446-35ccdc0b657f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MjYwOTEsIm5iZiI6MTcxNjQyNTc5MSwicGF0aCI6Ii8xMzkzNjUyODkvMzMyODc5NjA4LTVhYTFjMjUwLWFjNTgtNGQ4My1hNDQ2LTM1Y2NkYzBiNjU3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMDU2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2Y5NGJmODI3ZDhlZGU1NTVkZjdjNjAwMzk0MTUwM2IxNGM1YWVhOTM1Mjk0YWJhMmZmZjJmY2ZhMTA3MzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._pcQf_Lq1E_-cXe1VzVQINN8T1arb8hWnzundH6BHFM)
> 
> showing error
> 
> ![image](https://private-user-images.githubusercontent.com/139365289/332880040-2fabfb98-da0d-4b22-9b4c-f5b126f05793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MjYwOTEsIm5iZiI6MTcxNjQyNTc5MSwicGF0aCI6Ii8xMzkzNjUyODkvMzMyODgwMDQwLTJmYWJmYjk4LWRhMGQtNGIyMi05YjRjLWY1YjEyNmYwNTc5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMDU2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NThhMjRhOGNlN2UzMGE1M2U2ODc1YmI1NWJiZGM5Yzk1ZjU2NzMwYjdkOTFhNGQ3ZTFlN2VjZjRkYjliZTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9IbWim06_6Yqq1rW9mDOI9RU-gAl4DfYPPTHAIaEjv0)
> 
> console logs
> 
> ===== Application Startup at 2024-05-22 16:27:11 =====
> 
> 2024-05-22 16:27:35,067 | INFO | ------------------------------------------------------------ 2024-05-22 16:27:35,068 | INFO | Chat2Api v1.1.4 | https://github.com/lanqian528/chat2api 2024-05-22 16:27:35,068 | INFO | ------------------------------------------------------------ 2024-05-22 16:27:35,068 | INFO | Environment variables: 2024-05-22 16:27:35,068 | INFO | API_PREFIX: nai 2024-05-22 16:27:35,068 | INFO | AUTHORIZATION: [] 2024-05-22 16:27:35,068 | INFO | CHATGPT_BASE_URL: ['https://chatgpt.com'] 2024-05-22 16:27:35,068 | INFO | ARKOSE_TOKEN_URL: [] 2024-05-22 16:27:35,068 | INFO | PROXY_URL: [] 2024-05-22 16:27:35,068 | INFO | HISTORY_DISABLED: True 2024-05-22 16:27:35,068 | INFO | POW_DIFFICULTY: 000032 2024-05-22 16:27:35,068 | INFO | RETRY_TIMES: 3 2024-05-22 16:27:35,068 | INFO | ENABLE_GATEWAY: True 2024-05-22 16:27:35,068 | INFO | CONVERSATION_ONLY: True 2024-05-22 16:27:35,068 | INFO | ------------------------------------------------------------ 2024-05-22 16:27:35,074 | INFO | Started server process [1] 2024-05-22 16:27:35,074 | INFO | Waiting for application startup. 2024-05-22 16:27:35,074 | INFO | Application startup complete. 2024-05-22 16:27:35,076 | INFO | Uvicorn running on http://0.0.0.0:5005 (Press CTRL+C to quit)

Sorry, I don't know how to deploy on hugging face so I can't give you a solution
