### ISSUE TITLE
deta.space 部署错误

### ISSUE THREAD

**Issue by aston314** [lanqian528/chat2api#56]
Error Type:
AttributeError

Error Message:
module 'orjson' has no attribute 'JSONEncoder'

Logs:
time="2024-05-25T06:35:15Z" level=info msg="serving logs listener on sandbox.localdomain:1234" agent=logsApiAgent
TELEMETRY	Name: telemetry-extension	State: Already subscribed	Types: [Function]
[ERROR] AttributeError: module 'orjson' has no attribute 'JSONEncoder'
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1030, in _gcd_import
  File "", line 1007, in _find_and_load
  File "", line 986, in _find_and_load_unlocked
  File "", line 680, in _load_unlocked
  File "", line 850, in exec_module
  File "", line 228, in _call_with_frames_removed
  File "/var/task/_entry.py", line 1, in 
    from detalib.handler import handle
  File "/opt/python/detalib/handler.py", line 3, in 
    from . import handlers
  File "/opt/python/detalib/handlers.py", line 1, in 
    from .event import parse_event
  File "/opt/python/detalib/event.py", line 1, in 
    from .helpers import json
  File "/opt/python/detalib/helpers.py", line 16, in 
    class CustomJSONEncoder(json.JSONEncoder):
Stack Trace:
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "", line 1030, in _gcd_import

  File "", line 1007, in _find_and_load

  File "", line 986, in _find_and_load_unlocked

  File "", line 680, in _load_unlocked

  File "", line 850, in exec_module

  File "", line 228, in _call_with_frames_removed

  File "/var/task/_entry.py", line 1, in 
    from detalib.handler import handle

  File "/opt/python/detalib/handler.py", line 3, in 
    from . import handlers

  File "/opt/python/detalib/handlers.py", line 1, in 
    from .event import parse_event

  File "/opt/python/detalib/event.py", line 1, in 
    from .helpers import json

  File "/opt/python/detalib/helpers.py", line 16, in 
    class CustomJSONEncoder(json.JSONEncoder):

**Comment by lanqian528** [comment]
看不懂
