### ISSUE TITLE
curl报错，Less than 1 bytes/sec transferred the last 10 seconds

### ISSUE THREAD

**Issue by cloudsthere** [lanqian528/chat2api#81]
有一定概率出现以下报错

2|chat2api  | 2024-06-02 12:53:39,446 | ERROR | Exception in ASGI application
2|chat2api  | Traceback (most recent call last):
2|chat2api  |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 265, in __call__
2|chat2api  |     await wrap(partial(self.listen_for_disconnect, receive))
2|chat2api  |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 261, in wrap
2|chat2api  |     await func()
2|chat2api  |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 238, in listen_for_disconnect
2|chat2api  |     message = await receive()
2|chat2api  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 568, in receive
2|chat2api  |     await self.message_event.wait()
2|chat2api  |   File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
2|chat2api  |     await fut
2|chat2api  | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fbd07013400
2|chat2api  | During handling of the above exception, another exception occurred:
2|chat2api  |   + Exception Group Traceback (most recent call last):
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
2|chat2api  |   |     result = await app(  # type: ignore[func-returns-value]
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2|chat2api  |   |     return await self.app(scope, receive, send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
2|chat2api  |   |     await super().__call__(scope, receive, send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
2|chat2api  |   |     await self.middleware_stack(scope, receive, send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
2|chat2api  |   |     raise exc
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
2|chat2api  |   |     await self.app(scope, receive, _send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 85, in __call__
2|chat2api  |   |     await self.app(scope, receive, send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
2|chat2api  |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2|chat2api  |   |     raise exc
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2|chat2api  |   |     await app(scope, receive, sender)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 756, in __call__
2|chat2api  |   |     await self.middleware_stack(scope, receive, send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 776, in app
2|chat2api  |   |     await route.handle(scope, receive, send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
2|chat2api  |   |     await self.app(scope, receive, send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
2|chat2api  |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2|chat2api  |   |     raise exc
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2|chat2api  |   |     await app(scope, receive, sender)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 75, in app
2|chat2api  |   |     await response(scope, receive, send)
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 258, in __call__
2|chat2api  |   |     async with anyio.create_task_group() as task_group:
2|chat2api  |   |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
2|chat2api  |   |     raise BaseExceptionGroup(
2|chat2api  |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2|chat2api  |   +-+---------------- 1 ----------------
2|chat2api  |     | Traceback (most recent call last):
2|chat2api  |     |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 261, in wrap
2|chat2api  |     |     await func()
2|chat2api  |     |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 250, in stream_response
2|chat2api  |     |     async for chunk in self.body_iterator:
2|chat2api  |     |   File "/var/www/chat2api/chatgpt/chatFormat.py", line 117, in stream_response
2|chat2api  |     |     async for chunk in response:
2|chat2api  |     |   File "/usr/local/lib/python3.10/dist-packages/curl_cffi/requests/models.py", line 211, in aiter_lines
2|chat2api  |     |     async for chunk in self.aiter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
2|chat2api  |     |   File "/usr/local/lib/python3.10/dist-packages/curl_cffi/requests/models.py", line 246, in aiter_content
2|chat2api  |     |     raise chunk
2|chat2api  |     | curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details

**Comment by lanqian528** [comment]
看起来像你网络问题

**Comment by jonathanfan-ee** [comment]
我这边也有，xy的网关，美国的服务器
